language: java
install: true

os: linux
dist: xenial
jdk: openjdk8

script:
  - ./gradlew build

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
  - provider: releases
    api_key: "$GITHUB_OAUTH_TOKEN"
    file:
      - celebrium-core/build/libs/celebrium-core-${TRAVIS_TAG}.jar
      - celebrium-utils/build/libs/celebrium-utils-${TRAVIS_TAG}.jar
      - celebrium-web/build/libs/celebrium-web-${TRAVIS_TAG}.jar
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: ./gradlew bintrayUpload --info
    skip_cleanup: true
    dry-run: false
    on:
      tags: true